### ISSUE TITLE
Can't enable plugin / Install issues

### ISSUE THREAD

**Issue by bobloadmire** [srluge/DelugeSickbeardPlugin#1]
The sick beard plugin shows in deluge, but when i hit the check box and hit apply, it gets unchecked and won't enable. I have restarted delgue a few times. Using deluge on windows x64 with python 2.7. installed via the interface, .egg file.

**Comment by ArgGrr** [comment]
I am also having issues installing on FreeBSD (FreeNAS).
Looking at the log files (/var/tmp/deluged.log and deluge_web.log), I needed to make the /.config folder. Once made and permissions set right, the plugin on the windows client enabled. Its config page limited to a test box.
When trying to enable on the web client, I get the following error:

[ERROR   ] 20:15:29 pluginmanagerbase:146 Unable to instantiate plugin!
[ERROR   ] 20:15:29 pluginmanagerbase:147 'sickbeard/data/sickbeard.css'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/deluge/pluginmanagerbase.py", line 144
    instance = cls(plugin_name.replace("-", "_"))
  File "/usr/local/deluge/plugins/Sickbeard-0.1.0-py2.7.egg/sickbeard/__init__.py", l
    from webui import WebUI as _plugin_cls
  File "/usr/local/deluge/plugins/Sickbeard-0.1.0-py2.7.egg/sickbeard/webui.py", line
  File "/usr/local/deluge/plugins/Sickbeard-0.1.0-py2.7.egg/sickbeard/webui.py", line
  File "/usr/local/deluge/plugins/Sickbeard-0.1.0-py2.7.egg/sickbeard/common.py", lin
    return pkg_resources.resource_filename("sickbeard", os.path.join("data", filename
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1155,
    self, resource_name
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1852,
    return self._extract_resource(manager, zip_path)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1873,
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'sickbeard/data/sickbeard.css'

Unsure how to fix this.

**Comment by bkvamme** [comment]
Same behavior here. Windows 7 SP1 x86, python 2.7. I select the checkbox to enable the plugin, but as soon as I click Apply or OK, the box is deselected. Tried both Deluge 1.3.6 and 1.3.11.

**Comment by bkvamme** [comment]
Was however able to enable the plugin now when I changed server. 

Deluge: 1.3.11
Ubuntu 14.04.1

**Comment by srluge** [comment]
Plugin was developed and tested with Deluge server running on Debian and client Chrome on Ubuntu. 

@bkvamme have you had success integrating with SickRage?
@ArgGrr in plugins/DelugeSickbeardPlugin/sickbeard/webui.py, remove the line 'stylesheets   = [get_resource("sickbeard.css")]'. The plugin at the moment has all the css inline, and doesn't require this. 
@bobloadmire can you paste relevant logging?

**Comment by srluge** [comment]
Oh, and sorry for the late response. There was no traffic on this project for quite some time, hence I checked less regular the github pages / mail.

**Comment by bkvamme** [comment]
No worries!

No, I got the same error as @ArGrr. Will try to remove the reference now

**Comment by srluge** [comment]
@bkvamme Did you get one step further? Can I help?

**Comment by bkvamme** [comment]
Sorry, been busy...
Had a look, and I can't seem to find it? Is this client or server side?

Hilsen,
Bjarte Odin Kvamme

**Comment by bkvamme** [comment]
I looked in Program Files and App Data (Windows client)

Hilsen,
Bjarte Odin Kvamme

**Comment by bkvamme** [comment]
Btw, I found the following in:
C:\Users\Remote\AppData\Roaming\Python-Eggs\sickbeard-0.1.0-py2.7.egg-tmp\sickbeard\data\config.glade

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE glade-interface SYSTEM "glade-2.0.dtd">



<glade-interface>
  <widget class="GtkWindow" id="window1">
    <child>
      <widget class="GtkHBox" id="prefs_box">
        <property name="visible">True</property>
        <child>
          <widget class="GtkLabel" id="label1">
            <property name="visible">True</property>
            <property name="label" translatable="yes">Test config
value:</property>
          </widget>
        </child>
        <child>
          <widget class="GtkEntry" id="txt_test">
            <property name="visible">True</property>
            <property name="can_focus">True</property>
          </widget>
          <packing>
            <property name="position">1</property>
          </packing>
        </child>
      </widget>
    </child>
  </widget>
</glade-interface>

Hilsen,
Bjarte Odin Kvamme

**Comment by srluge** [comment]
The file resides server side. When you located the DelugeSickbeard plugin; the file is in sickbeard/webui.py.

As an alternative, you can install the plugin directly from source (git clone). I just committed a fix. Haven't added instructions to the documentation on how to do install from source yet. But with some python background this is doable.

**Comment by srluge** [comment]
Created (untested) instructions on how to install plugin from git source: https://srluge.github.io/DelugeSickbeardPlugin/documentation/development/

**Comment by stormrev** [comment]
Hi srluge, I have an old NAS running ubuntu 10.04 with python2.6 and deluge1.3.12. 
Can't upgrade to python2.7.
The plugin install fails with following error, can you help sort this out?
many thanks

[ERROR   ] 22:01:57 pluginmanagerbase:146 Unable to instantiate plugin!
[ERROR   ] 22:01:57 pluginmanagerbase:147 Error when calling the metaclass bases
    a new-style class can't have only classic bases
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/deluge-1.3.12-py2.6.egg/deluge/pluginmanagerbase.py", line 144, in enable_plugin
    instance = cls(plugin_name.replace("-", "_"))
  File "build/bdist.linux-i686/egg/sickbeard/__init__.py", line 25, in **init**
    from core import Core as _plugin_cls
  File "build/bdist.linux-i686/egg/sickbeard/core.py", line 25, in <module>
  File "build/bdist.linux-i686/egg/sickbeard/sickbeard.py", line 24, in <module>
  File "build/bdist.linux-i686/egg/sickbeard/log.py", line 93, in <module>
  File "/usr/lib/python2.6/abc.py", line 79, in __new__
    cls = super(ABCMeta, mcls).**new**(mcls, name, bases, namespace)
TypeError: Error when calling the metaclass bases
    a new-style class can't have only classic bases
[ERROR   ] 22:01:58 rpcserver:304 Exception calling RPC request: 'PreferencesManager' object has no attribute 'do_config_set_func'
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/deluge-1.3.12-py2.6.egg/deluge/core/rpcserver.py", line 299, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "build/bdist.linux-i686/egg/scheduler/core.py", line 176, in set_config
    self.do_schedule(False)
  File "build/bdist.linux-i686/egg/scheduler/core.py", line 144, in do_schedule
    self.__apply_set_functions()
  File "build/bdist.linux-i686/egg/scheduler/core.py", line 130, in __apply_set_functions
    component.get("PreferencesManager").do_config_set_func(setting, core_config[setting])
AttributeError: 'PreferencesManager' object has no attribute 'do_config_set_func'
[ERROR   ] 22:01:59 rpcserver:304 Exception calling RPC request: 'PreferencesManager' object has no attribute 'do_config_set_func'
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/deluge-1.3.12-py2.6.egg/deluge/core/rpcserver.py", line 299, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "build/bdist.linux-i686/egg/scheduler/core.py", line 176, in set_config
    self.do_schedule(False)
  File "build/bdist.linux-i686/egg/scheduler/core.py", line 144, in do_schedule
    self.__apply_set_functions()
  File "build/bdist.linux-i686/egg/scheduler/core.py", line 130, in __apply_set_functions
    component.get("PreferencesManager").do_config_set_func(setting, core_config[setting])
AttributeError: 'PreferencesManager' object has no attribute 'do_config_set_func'

**Comment by vember31** [comment]
I'm also struggling with the box that says "test config value:" after enabling the plugin.  I'm running Linux Mint 17 and Deluge 1.3.6.  No issues otherwise when enabling or installing.  I followed your instructions to build from source, which I saw included commenting out the stylesheet line in webui.py.  Unfortunately this did not help.

What should I do next?  One thing I also noticed is that after enabling the plugin, I don't have sickbeard.conf in my ~/config/deluge directory.  I read in your instructions that the conf file is supposed to be generated upon first enabling.  Would that have anything to do with it?  Thanks and let me know how I can help!

**Comment by pOaW** [comment]
I'm in the same boat as vember31, I get the "test config value" box... when the plugin allows me to click the checkbox... sometimes it will uncheck when I click apply.

**Comment by romprod** [comment]
Hi,

I'm having issues also install this plugin on a Windows platform.

I get the following error message when I try to enabled the plugin.

`Unable to instantiate plugin!
No module named handlers
Traceback (most recent call last):
  File "deluge\pluginmanagerbase.py", line 144, in enable_plugin
  File "c:\users\user\appdata\roaming\deluge\plugins\sickbeard-0.1.0-py2.7.egg\sickbeard\__init__.py", line 25, in __init__
    from core import Core as _plugin_cls
  File "c:\users\user\appdata\roaming\deluge\plugins\sickbeard-0.1.0-py2.7.egg\sickbeard\core.py", line 22, in <module>
ImportError: No module named handlers`

I'm using Windows10
Deluge 1.3.13
